name: Create draft release

on:
  push:
    tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install npm dependencies
        run: npm install
      - name: Compile 
        run: tsc
      - name: Bundle
        run: sh scripts/bundle.sh
      - name: Pack
        run: sh scripts/pack.sh
      - name: Get version
        id: version
        run: echo "##[set-output name=value;]$(sh scripts/get-version.sh)"
      - name: Rename index.js for upload
        run: mv ./bundles/index.js ./bundles/cogni-${{ steps.version.outputs.value }}.js
      - name: Create draft with uploads
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./build/cogni-${{ steps.version.outputs.value }}-windows-x64
            ./build/cogni-${{ steps.version.outputs.value }}-windows-x86
            ./build/cogni-${{ steps.version.outputs.value }}-linux-x64
            ./build/cogni-${{ steps.version.outputs.value }}-linux-x86
            ./build/cogni-${{ steps.version.outputs.value }}-macos-x64
            ./bundles/cogni-${{ steps.version.outputs.value }}.js
